# Generated by Django 4.1 on 2022-08-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='category',
            field=models.CharField(choices=[('CG', 'Closed Guard'), ('BG', 'Butterfly  Guard'), ('SG', 'Spider Guard'), ('LG', 'Lasso Guard'), ('DLR', 'De La Riva Guard'), ('HGB', 'Half Guard Bottom'), ('HGT', 'Half Guard Top'), ('SCB', 'Side Control Bottom'), ('SCT', 'Side Control Top'), ('MT', 'Mount Top'), ('ME', 'Mount Escape'), ('BC', 'Back Control'), ('BE', 'Back Escape'), ('KOB', 'Knee On Belly'), ('NS', 'North South'), ('GP', 'Guard Pass'), ('GR', 'Guard Retention'), ('TD', 'Takedown'), ('WU', 'Warmup'), ('OT', 'Other')], default='CG', max_length=4),
        ),
    ]
